server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security?serverTimezone=Asia/Seoul
    username: myadmin
    password: myadmin

  jpa:
    hibernate:
      ddl-auto: update #create update none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
