server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security?serverTimezone=Asia/Seoul
    username: myadmin
    password: myadmin

  jpa:
    hibernate:
      ddl-auto: update #create update none
    properties:
      hibernate:
        show-sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 862823764750-ahj2aoimbbtuvq0qnhscgnakuuqh5keo.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile