server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security?serverTimezone=Asia/Seoul
    username: myadmin
    password: myadmin

  jpa:
    hibernate:
      ddl-auto: update #create update none
    properties:
      hibernate:
        show-sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 862823764750-ahj2aoimbbtuvq0qnhscgnakuuqh5keo.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: rYC285Xsu8jGekZ5wHgW
            client-secret: d3FbVxxv0J
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원 정보는 json으로 받는데 response라는 키값으로 네이버가 리턴해줌